### PR TITLE
add peasocket

### PR DESCRIPTION
**Pull request by soypat**
I have not run the benchmarks, the steps seemed a bit too low level on the linux side for me to try them out. nonetheless I've left a barebones example on how I think I'd solve the benchmark with peasocket.

### CODE REVIEW

**Comment by lesismal** [comment]
please also modify the script, and will be better to provide the benchmark output.

**Comment by soypat** [comment]
I tried running the benchmark as per the instructions using the shellscript and it seems to run forever. How long does it usually take? Also setting `ulimit` returns an error:
```
$ ulimit -n 2000500
bash: ulimit: open files: cannot modify limit: Operation not permitted
```
using sudo naturally:
```
$ sudo ulimit -n 2000500
sudo: ulimit: command not found
```

**Comment by lxzan** [comment]
how about ulimit -n 1000000 ?

**Comment by lxzan** [comment]
It takes about 1 minute to run benchmark.sh

**Pull request closed without merging**
